In [13]:
# Operaciones con strings 

s = "The universe doesn't allow perfection"
palabras = s.split()
print(palabras)

['The', 'universe', "doesn't", 'allow', 'perfection']


In [5]:
s = "El pasado puede doler, pero tal como yo lo veo, puedes huir o aprender de él"
contador = 0
for letra in s:
    if letra != " ":
        contador += 1
print(contador)

61


In [6]:
s = "If you wish to make an apple pie from scratch, you must first invent the universe"
r = s.replace('apple', 'banana')
print (r)

If you wish to make an banana pie from scratch, you must first invent the universe


In [12]:
frase = "The diameter of {planet} is {diameter} kilometers".format(planet = "Earth", diameter = "12742")
print (frase)

The diameter of Earth is 12742 kilometers


In [18]:
# Operaciones con listas

lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
new_list = lst[:3]
print(new_list)

[0, 1, 2]


In [29]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

new_list = lst[-3:]
print(new_list)

[8, 9, 10]


In [30]:
# Números pares 

lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
par_number = []

for i in lst:
    if( i % 2 ) == 0:
        par_number.append(i)
            
print (par_number)

[0, 2, 4, 6, 8, 10]


In [31]:
# Revertir la lista

lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
lst.reverse()

print(lst)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [41]:
# Ordenar de menor a mayor

lst = [4, 1, 6, 12, 3, 2, 1, 7, 1, 0, 14]

num_ordenados = sorted(lst)

print (num_ordenados)

[0, 1, 1, 1, 2, 3, 4, 6, 7, 12, 14]


In [40]:
# Imprimir "Hello"

lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

word_hello = lst[3][1][2][0]
    
print (word_hello)

hello


In [50]:
# Ordenar la siguiente lista de diccionarios de mayor a menor y de menor a mayor según el valor de 'age'

lst = [
    {
        "name": "A",
        "age": 12
    },
        {
        "name": "B",
        "age": 22
    },
        {
        "name": "C",
        "age": 2
    },
        {
        "name": "D",
        "age": 4
    },
        {
        "name": "E",
        "age": 42
    },
]

In [55]:
# Funciones 

def obtener_dominio(email):
    partes_email = email.split('@')

    if len(partes_email) == 2:
        return partes_email[1]
    else:
        return None  # None si no es válido

email = "karolfuentescaro@gmail.com"
obtener_dominio = obtener_dominio(email)

print("Email:", email)
print("Email domain:", obtener_dominio)

Email: karolfuentescaro@gmail.com
Email domain: gmail.com


In [ ]:
# filtrar palabras que no empiezan en s

seq = ['soup', 'dog', 'salad', 'cat', 'great']

filtered_words = list(filter(lambda word: word[0] != 's', seq))

print(filtered_words)

In [69]:
def verify_word(frase, palabra):
    return palabra in frase

entered_phrase = "Adventure of a lifetime"
entered_word = "cat"

# Llamar a la función y mostrar el resultado
resultado = verify_word(entered_phrase, entered_word)

print(resultado)

False


In [74]:
# Verificar si está dog en la frase

s = "Is there a dog here?"

def contiene_palabra_dog(cadena):
    return 'dog' in cadena
resultado = contiene_palabra_dog(s)

print(resultado)

True


In [76]:
def counter_dog(phrase):
    return phrase.lower().count('dog')

s = "This dog runs faster than the other dog dude!"
result = counter_dog(s)

print(result)

2


In [ ]:
# Numpy Básico

import numpy as np

In [82]:
# Arreglo de 10 ceros 
import numpy as np

zeros_array = np.zeros(10)

print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [83]:
# Arreglo de 10 unos
import numpy as np

ones_array = np.ones(10)

print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [88]:
# Arreglo de 10 cincos
import numpy as np

five_array = np.ones(10) * 5

print(five_array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [91]:
# Crea un areglo de enteros (int) de 10 a 50
import numpy as np

num_enteros = np.arange(10, 51)

print(num_enteros)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [92]:
#Matriz 3x3 de 0-8
import numpy as np

matriz = np.arange(9).reshape(3, 3)

print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [96]:
# Array aleatorio [20] entre 10 y 100
import numpy as np

random_array = np.random.randint(10, 101, size=20)

print(random_array)

[56 49 73 18 51 65 98 27 87 31 97 10 25 68 71 78 72 84 51 96]


In [98]:
# Pandas Básico

import pandas as pd

In [108]:
# Leer el archivo CSV y crear un DataFrame llamado 'sal'
import pandas as pd

sal = pd.read_csv('Salaries.csv')

In [109]:
# Revisar el head del dataframe (usar el métdodo head())
import pandas as pd

sal = pd.read_csv('Salaries.csv')

print(sal.head())

   Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisc

In [115]:
# Basepay
import pandas as pd

sal = pd.read_csv('Salaries.csv')

promedio_basepay = sal['BasePay'].mean()

print(f"El BasePay: {promedio_basepay}")

El BasePay: 66325.4488404877


In [117]:
import pandas as pd

sal = pd.read_csv('Salaries.csv')
max_overtimepay = sal['OvertimePay'].max()

print(f"La cantidad más alta de OvertimePay es: {max_overtimepay}, en el conjunto de datos")

La cantidad más alta de OvertimePay es: 245131.88, en el conjunto de datos


In [120]:
# ¿Cuál es el cargo de JOSEPH DRISCOLL? 

import pandas as pd

sal = pd.read_csv('Salaries.csv')
trabajador_name = sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']
cargo_jd = joseph_driscoll_info['JobTitle'].values[0]

print(f"El cargo de JOSEPH DRISCOLL es: {cargo_jd}")

El cargo de JOSEPH DRISCOLL es: CAPTAIN, FIRE SUPPRESSION


In [123]:
# ¿Cuál es el nombre de la persona mejor pagada (incluidos los beneficios)?

import pandas as pd

sal = pd.read_csv('Salaries.csv')
best_paid = sal.loc[sal['TotalPayBenefits'].idxmax()]
name_bpaid = best_paid['EmployeeName']

print(f"El empleado mejor pagado (con beneficios) es: {name_bpaid}")

El empleado mejor pagado (con beneficios) es: NATHANIEL FORD


In [127]:
# ¿Cuántos títulos de trabajo únicos hay?
import pandas as pd

sal = pd.read_csv('Salaries.csv')
unique_titles = sal['JobTitle'].nunique()

print(f"Hay {unique_titles} títulos de trabajo únicos.")

Hay 2159 títulos de trabajo únicos.


In [4]:
import pandas as pd 

df = pd.read_csv("datitos.csv")


In [7]:
def opciones():
    print("¿Cómo lo quieres ordenar?")
    print("1. Ordenar por edad")
    print("2. Ordenar por número de hermanos")
    print("3. Salir")

    opcion = int(input("Digite la opción deseada: "))
    return opcion

def ordenar_columna(df, columna, orden):
    if orden == "ascendente":
        df = df.sort_values(columna, ascending=True)
    elif orden == "descendente":
        df = df.sort_values(columna, ascending=False)
    else:
        print("No existe la opción escrita")
        return

    print(df.to_string())

def main():
    while True:
        opcion = opciones()
        if opcion == 1:
            columna = "Edad"
        elif opcion == 2:
            columna = "# De hermanos"
        elif opcion == 3:
            break
        else:
            print("Opción no válida.")
            continue

        orden = input("Digite el tipo de ordenamiento (ascendente o descendente): ")
        ordenar_columna(df.copy(), columna, orden)

if __name__ == "__main__":
    main()


¿Cómo lo quieres ordenar?
1. Ordenar por edad
2. Ordenar por número de hermanos
3. Salir
